// Login types
export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = "LOGIN_ERROR";

// Signup types
export const SIGNUP_START = 'SIGNUP_START';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';

// Authentication types
export const AUTHENTICATION_START = 'AUTHENTICATION_START';
export const AUTHENTICATION_ERROR = 'AUTHENTICATION_ERROR';
export const AUTHENTICATION_SUCCESS = 'AUTHENTICATION_SUCCESS';
export const AUTHENTICATION_TOKEN_ERROR = 'AUTHENTICATION_TOKEN_ERROR';

// Open modal types
export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';

// Posts types
export const CREATEPOST_START = 'CREATEPOST_START';
export const CREATEPOST_SUCCESS = 'CREATEPOST_SUCCESS';
export const CREATEPOST_ERROR = 'CREATEPOST_ERROR';
export const CREATEPOST_UPLOAD_PROGRESS = 'CREATEPOST_UPLOAD_PROGRESS';

export const GET_FOLLOWING_POSTS_START = 'GET_FOLLOWING_POSTS_START';
export const GET_FOLLOWING_POSTS_SUCCESS = "GET_FOLLOWING_POSTS_SUCCESS";
export const GET_FOLLOWING_POSTS_ERROR = 'GET_FOLLOWING_POSTS_ERROR';

export const SET_POST_LIKE_SUCCESS = 'SET_POST_LIKE_SUCCESS';
export const SET_POST_LIKE_ERROR = 'SET_POST_LIKE_ERROR';

export const SET_POST_COMMENT_SUCCESS = 'SET_POST_COMMENT_SUCCESS';
export const SET_POST_COMMENT_ERROR = 'SET_POST_COMMENT_ERROR';

export const GET_EXPLORE_POSTS_START = 'GET_EXPLORE_POSTS_START';
export const GET_EXPLORE_POSTS_SUCCESS = 'GET_EXPLORE_POSTS_SUCCESS';
export const GET_EXPLORE_POSTS_ERROR = 'GET_EXPLORE_POSTS_ERROR';